#!/bin/bash
confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='1FivYRaIAFmLK8pRjISx6LXA7z16MGIJv -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
echo $confirm
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=1FivYRaIAFmLK8pRjISx6LXA7z16MGIJv" -O creditcard.csv && rm -rf /tmp/cookies.txt
mv creditcard.csv ./data/